### ISSUE TITLE
Guidance on certificate

### ISSUE THREAD

**Issue by manu-silicon** [tngan/express-saml2#62] opened 2017-05-09 04:38 UTC
I've been successful at running the samples and I'm trying to setup my own identity provider in node.js/express/express-saml2 and I'm testing it against a locally run instance of gitlab community. Trying naively, it almost works as from gitlab I can go to my identity provider, login and post the response. But then gitlab reply with:

```Could not authenticate you from SAML because "Found an unexpected number of signature element. saml response rejected".```

So most likely I'm doing something wrong but not sure what.

One thing that I could not find is a clear explanation of all the certificates and keys. It does not say what they are, how to generate them properly, if they are required. It would be nice to have a little bit of guidance here.

For example are the X509Certificate in the metadata_idp1.xml file related to the key we can find in key/idp?

**Comment by tngan** [comment] 2017-05-09 15:12
@manu-silicon Thank you so much for your valuable feedback.

The signing/encryption key can be generated using the following commands.

```bash
$ openssl genrsa -passout pass:foobar -out encryptKey.pem 4096
$ openssl req -new -x509 -key encryptKey.pem -out encryptionCert.cer -days 3650
```

If you are using 3rd party identity provider like OneLogin and Okta, the IdP metadata is allowed for you to download instead of creating manually. In this module, a helper function allows you to export the metadata after you have constructed the entity [(See here)](https://express-saml2.js.org/metadata_distribution.html).

For the above error, `Could not authenticate you from SAML because "Found an unexpected number of signature element. saml response rejected".`.  It really depends on how Gitlab (SP) handles the response sent from the express-saml2's IdP, it would be good if you can provide the SAML response as well.

I thought Gitlab is using omniauth-saml (https://about.gitlab.com/2016/03/30/feature-highlight-saml/), and this one relies on ruby-saml maintained by OneLogin, so the error could be thrown from the following lines of code.

https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L548-L550

I think the signature element might not be constructed well fit to the Gitlab's context, are you using the default SAML response or using a customize template in express-saml2 ?

**Comment by manu-silicon** [comment] 2017-05-10 04:52
Thanks for getting back to me and the command line for generating the signing and encryption key. I've taken care of that.

I'm trying to build my own IdP so I'm testing the gitlab as a service provider and I'm following the gitlab instructions to enable SAML.

Gitlab provides me with the following metadata file:
```
<?xml version='1.0' encoding='UTF-8'?>
<md:EntityDescriptor ID='_a1eaa7d4-4ea7-4a8d-a36a-fa280e7a4f50' entityID='https://gitlab' xmlns:md='urn:oasis:names:tc:SAML:2.0:metadata' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion'>
    <md:SPSSODescriptor AuthnRequestsSigned='false' WantAssertionsSigned='false' protocolSupportEnumeration='urn:oasis:names:tc:SAML:2.0:protocol'>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
        <md:AssertionConsumerService Binding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST' Location='https://gitlab/users/auth/saml/callback' index='0' isDefault='true'/>
        <md:AttributeConsumingService index='1' isDefault='true'><md:ServiceName xml:lang='en'>Required attributes</md:ServiceName>
            <md:RequestedAttribute FriendlyName='Email address' Name='email' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'/>
            <md:RequestedAttribute FriendlyName='Full name' Name='name' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'/>
            <md:RequestedAttribute FriendlyName='Given name' Name='first_name' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'/>
            <md:RequestedAttribute FriendlyName='Family name' Name='last_name' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'/>
        </md:AttributeConsumingService>
    </md:SPSSODescriptor>
</md:EntityDescriptor>
```
and my Idp metadata is:

```
<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://idp/sso/metadata/gitlab" ID="pfxbcb19ef2-5fa9-d581-a80e-d6ba2be0e2de">
    <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:KeyDescriptor use="signing">
            <ds:KeyInfo Id="SM4cee9750ee17bb2f60ddbe556a2798218f7a5bbed"
             xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>...</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:KeyDescriptor use="encryption">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>...</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:entity</md:NameIDFormat>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:kerberos</md:NameIDFormat>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName</md:NameIDFormat>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName</md:NameIDFormat>        
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp/sso/login/gitlab"/>
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://idp/sso/login/gitlab"/>
        <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp/sso/logout/gitlab"/>
        <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://idp/sso/logout/gitlab"/>
    </md:IDPSSODescriptor>
</md:EntityDescriptor>
```
I've captured the SAML request and response using the SAML Chrome panel plugin and here is what I have:
```
<samlp:AuthnRequest AssertionConsumerServiceURL='https://gitlab/users/auth/saml/callback'
    Destination='https://idp/sso/login/gitlab' ID='_01c63c8d-832c-4371-9d92-f5a71d1f9256'
    IssueInstant='2017-05-10T04:42:05Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion'
    xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'>
    <saml:Issuer>https://gitlab</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'/></samlp:AuthnRequest>
```

And here is the response:
```
<samlp:Response Destination="https://gitlab/users/auth/saml/callback"
    ID="5745299a-d46a-4a1f-8bfa-e13112e2648a" InResponseTo="_01c63c8d-832c-4371-9d92-f5a71d1f9256"
    IssueInstant="2017-05-10T04:42:05.453Z" Version="2.0"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer>https://idp/sso/metadata/gitlab</saml:Issuer>
    <samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status>
    <saml:Assertion ID="6936418b-993a-417c-81ff-c03034fb7fa1" IssueInstant="2017-05-10T04:42:05.453Z"
        Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
        <saml:Issuer>https://idp/sso/metadata/gitlab</saml:Issuer>
        <saml:Subject>
            <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">emmanuel.stapf@xenko.com</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData InResponseTo="_01c63c8d-832c-4371-9d92-f5a71d1f9256"
                NotOnOrAfter="2017-05-10T04:47:05.453Z" Recipient="https://gitlab"/></saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2017-05-10T04:42:05.453Z" NotOnOrAfter="2017-05-10T04:47:05.453Z">
            <saml:AudienceRestriction>
                <saml:Audience>https://gitlab</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
    </saml:Assertion>
</samlp:Response>
```

You are right that the line of code you selected is the culprit. In my case I have 0 signature_nodes and true for signature_elements.empty? I tried to set `WantAuthnRequestsSigned` to true in my IdP but then the error from ruby-saml occurs at line https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L534

Thanks for any insight you can provide!

**Comment by tngan** [comment] 2017-05-10 12:51
Apparently the error is not caused by he request but response, so changing the `wantAuthnRequestSigned` is not workable.

In our IdP, signing of assertion is determined by the pairwise SP setting. `WantAssertionsSigned` should be defined in the SP metadata or set `wantAssertionSigned` as true in the SP setting object when you construct your SP.

For login SP, the user information for example the email, first name, last name ...etc, will be included in the assertion, and sign the assertion.

**Comment by tngan** [comment] 2017-05-10 13:41
@manu-silicon However, the SP metadata states that `AuthnRequestsSigned='false'` and `WantAssertionsSigned='false'`, so the unsigned request is fine and the response is supposed to be not signed as well.

It's interesting, so I am considering to open a new ticket for Gitlab example.

**Comment by manu-silicon** [comment] 2017-05-10 14:21
Is there anything I can do to help in this case?

**Comment by tngan** [comment] 2017-05-10 14:29
@manu-silicon Would you like to share how you setup your Gitlab server, following this [tutorial](https://docs.gitlab.com/ee/integration/saml.html) ?

**Comment by manu-silicon** [comment] 2017-05-10 14:39
I've followed this tutorial to the letter. The only difference is that my idp_cert_fingerprint. For that I put the one I got from the signing key.

**Comment by manu-silicon** [comment] 2017-05-10 14:41
To be complete, here is what I have:

```
### OmniAuth Settings
###! Docs: https://docs.gitlab.com/ce/integration/omniauth.html
gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
gitlab_rails['omniauth_block_auto_created_users'] = false
gitlab_rails['omniauth_providers'] = [
    {
      name: 'saml',
      args: {
               assertion_consumer_service_url: 'https://gitlab/users/auth/saml/callback',
               idp_cert_fingerprint: 'd5:bc:69:b2:f0:cb:0d:36:20:cd:c9:22:8f:2a:17:eb:53:58:c8:e6',
               idp_sso_target_url: 'https://idp/sso/login/gitlab',
               idp_slo_target_url: 'https://idp/sso/logout/gitlab',
               issuer: 'https://gitlab',
               name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'
             },
      label: 'Login' # optional label for SAML login button, defaults to "Saml"
    }
  ]
```

**Comment by tngan** [comment] 2017-05-10 15:08
@manu-silicon In fact, how do you obtain the `idp_cert_fingerprint` ?

**Comment by manu-silicon** [comment] 2017-05-10 15:26
I used the cert from the signing key on the IdP and then got the SHA1 of that. I used `cat cert | openssl -sha1`.

Manu

________________________________

**Comment by tngan** [comment] 2017-05-10 16:21
@manu-silicon Nice, I will keep you posted in this thread so don't close this issue.

**Comment by manu-silicon** [comment] 2017-05-11 04:16
I also tried this to get the idp_cert_fingerprint:
```openssl x509 -noout -fingerprint -sha1 -inform pem -in signing.crt```

On the gitlab side, it is also not clear which certification you are supposed to use. I tried, the https one, the signing or the encryption crt and non seems to have an effect.

**Comment by tngan** [comment] 2017-05-11 10:00
Yes, I am going to test the SAML approach using dockerize gitlab within this week, not sure if it restricts to https.

**Comment by tngan** [comment] 2017-05-13 06:32
@manu-silicon Let me close this issue first, I will update the progress in the thread #12 within today.

**Closed by tngan** 2017-05-13 06:32 UTC
Labels: question, v1, v2

**Comment by tngan** [comment] 2017-05-13 11:58
@manu-silicon I have made some progress in it, hopefully it can be resolved soon. You can checkout here. #12
